apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-sa-binding
subjects:
- kind: ServiceAccount
  name: my-serviceaccount     # ServiceAccount name
  namespace: default          # Namespace where ServiceAccount lives
roleRef:
  kind: ClusterRole
  name: pod-reader-clusterrole
  apiGroup: rbac.authorization.k8s.io
